FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./ 
RUN npm install --only=production

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY app.js ./ 
COPY package.json ./
EXPOSE 8080
ENTRYPOINT ["node"]
CMD ["app.js" , "development"] 
