FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./ 
RUN npm install --only=production

FROM gcr.io/distroless/nodejs24-debian13
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY app.js ./ 
COPY package.json ./
EXPOSE 8080
USER 65532
CMD ["app.js" , "development"] 
