name: Basic_Node_Pipeline

on: workflow_dispatch

jobs:
  Running-Node-App:
    runs-on: ["self-hosted" , "wsl-sakthi"]

    steps:
      - name: Cloning_Code
        uses: actions/checkout@v7
        
      - name: Installing Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Installing Dependencies
        run: npm install

      - name: Run Application
        run: |
          node app.js &
          sleep 5
          curl http://localhost:8080
          pkill -f "node app.js"
