name: Basic_Node_Pipeline

on: 
  workflow_dispatch:

    inputs:
      Environment: 
        description: "Choose which environment to use/deploy"
        required: true
        default: "Development"
        type: choice
        options:
          - Production
          - Development
      Port:
        description: "Dev=8080 & Prod=5000"
        required: true
        default: "8080"
        type: choice
        options:
          - 5000
          - 8080
  
jobs:
  Running-Node-App:
    runs-on: ["self-hosted" , "wsl-sakthi"]

    steps:
      - name: Cloning_Code
        uses: actions/checkout@v7
        
      - name: Installing Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Installing Dependencies
        run: npm install

      - name: Run Application
        run: |
          node app.js ${{ github.event.inputs.Environment }} &
          sleep 5
          curl http://localhost:${{ github.event.inputs.Port }}
          pkill -f "node app.js"
