name: Test_pipeline_push

on:
  #push:
    #branches: ["main"]
  
  workflow_dispatch: 

jobs:
  demo-pull:
    runs-on: ["self-hosted" , "wsl-sakthi"]

    steps:
      - name: Testing Pipeline
        run: echo "Pipeline Check"
