name: SonarQube_Pipeline

on: 
  pull_request:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  SonarQube:
    runs-on: [self-hosted , wsl-sakthi]

    steps:
      - name: Cloning Code
        uses: actions/checkout@v7

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8
        with:
          args: >
            -Dsonar.projectKey=NodeApp 
            -Dsonar.sources=. 
            -Dsonar.host.url=${{ vars.SONAR_LOGIN_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
